compute_score – ForPCA
compute_score Subroutine
Seyed Ali Ghasemi
10 statements
Source File
private pure subroutine compute_score(this)
Type Bound
tpca
Arguments
Type Intent Optional Attributes Name
class(tpca), intent(inout) :: this
Calls
Called by
Contents
Source Code
compute_score
Source Code
   pure subroutine compute_score(this)
      class(tpca), intent(inout) :: this
      integer                    :: i, j
      allocate(this%score(this%nrow,this%ncol))
      do i = 1, this%nrow
         do j = 1, this%npc
            this%score(i, j) = dot_product(this%mean_data(i, :), this%coeff(:, j))
         end do
      end do
   end subroutine compute_score
Call graph
compute_score calls coeff, mean_data, score
pca calls compute_score