compute_coeff – ForPCA
compute_coeff Subroutine
Seyed Ali Ghasemi
37 statements
Source File
private pure subroutine compute_coeff(this)
Uses
forsvd
Type Bound
tpca
Arguments
Type Intent Optional Attributes Name
class(tpca), intent(inout) :: this
Calls
Called by
Contents
Source Code
compute_coeff
Source Code
   pure subroutine compute_coeff(this)
      use forsvd
      class(tpca), intent(inout)               :: this
      real(rk), dimension(this%ncol)           :: mean
      real(rk), dimension(this%ncol,this%ncol) :: cov
      integer                                  :: i
      mean = sum(this%matrix, dim=1) / real(this%nrow, kind=rk)
      allocate(this%mean_data(this%nrow,this%ncol))
      do i = 1, this%nrow
         this%mean_data(i, :) = this%matrix(i, :) - mean
      end do
      cov = matmul(transpose(this%mean_data), this%mean_data)/real(this%nrow - 1, kind=rk)
      select case(this%method)
       case('svd')
         block
            real(rk), dimension(this%ncol,this%ncol) :: U
            real(rk), dimension(this%ncol,this%ncol) :: VT
            real(rk), dimension(this%ncol)           :: S
            call svd(cov, U,S,VT)
            this%latent = S**2/(this%ncol-1)
            this%coeff  = transpose(VT)
         end block
       case('eig')
         block
            logical,  dimension(this%ncol) :: mask
            integer,  dimension(this%ncol) :: order
            call eig(cov, this%coeff, this%latent)
            ! Sort
            mask = .true.
            do i = lbound(this%latent,1), ubound(this%latent,1)
               order(i) = maxloc(this%latent,1,mask)
               mask(order(i)) = .false.
            end do
            this%latent = this%latent(order)
            this%coeff  = this%coeff(:,order)
         end block
      end select
   end subroutine compute_coeff
Call graph
compute_coeff calls coeff, eig, latent, mask, matrix, mean_data, order, svd
pca calls compute_coeff