pca – ForPCA
pca Subroutine
Seyed Ali Ghasemi
33 statements
Source File
private impure subroutine pca(this, matrix, npc, method, coeff, score, latent, explained, matrix_app)
Type Bound
tpca
Arguments
Type Intent Optional Attributes Name
class(tpca), intent(inout) :: this
real(kind=rk), intent(in), dimension(:,:) :: matrix
integer, intent(in), optional :: npc
character(len=*), intent(in), optional :: method
real(kind=rk), intent(out), dimension(:,:), allocatable :: coeff
real(kind=rk), intent(out), optional, dimension(:,:), allocatable :: score
real(kind=rk), intent(out), optional, dimension(:), allocatable :: latent
real(kind=rk), intent(out), optional, dimension(:), allocatable :: explained
real(kind=rk), intent(out), optional, dimension(:,:), allocatable :: matrix_app
Calls
Called by
Source Code
   impure subroutine pca(this, matrix, npc, method, coeff, score, latent, explained, matrix_app)
      class(tpca),                           intent(inout)         :: this
      real(rk), dimension(:,:),              intent(in)            :: matrix
      integer,                               intent(in),  optional :: npc
      character(*),                          intent(in),  optional :: method
      real(rk), dimension(:,:), allocatable, intent(out)           :: coeff
      real(rk), dimension(:,:), allocatable, intent(out), optional :: score
      real(rk), dimension(:),   allocatable, intent(out), optional :: latent
      real(rk), dimension(:),   allocatable, intent(out), optional :: explained
      real(rk), dimension(:,:), allocatable, intent(out), optional :: matrix_app
#if defined(USE_COARRAY)
      if (this_image() == 1) then
#endif
         call this%initialize(matrix, npc, method)
#if defined(USE_COARRAY)
      end if
#endif
      call this%compute_coeff()
      coeff = this%coeff
#if defined(USE_COARRAY)
      if (this_image() == 1) then
#endif
         if(present(score)) then
            call this%compute_score()
            score = this%score
         end if
         if(present(latent)) then
            latent = this%latent
         end if
         if(present(explained)) then
            call this%cmp_explained_variance()
            explained = this%explained_variance*100.0_rk
         end if
#if defined(USE_COARRAY)
      end if
#endif
      if(present(matrix_app)) then
         call this%reconstruct_data()
         matrix_app = this%matrix_app
      end if
   end subroutine pca
Call graph
pca calls cmp_explained_variance, compute_coeff, compute_score, initialize, reconstruct_data
compute_coeff calls eig, mask, order, svd
benchmark calls pca
test1 calls pca