reconstruct_data – ForPCA
reconstruct_data Subroutine
Seyed Ali Ghasemi
17 statements
Source File
private impure subroutine reconstruct_data(this)
Uses
formatmul
Type Bound
tpca
Arguments
Type Intent Optional Attributes Name
class(tpca), intent(inout) :: this
Called by
Source Code
   impure subroutine reconstruct_data(this)
      use formatmul, only: matmul
      class(tpca), intent(inout)             :: this
      real(rk), dimension(:, :), allocatable :: X_centered
      real(rk), dimension(:, :), allocatable :: pca_X
      integer                                :: i, j
#if defined(USE_COARRAY)
      if (this_image() == 1) then
#endif
         X_centered = this%matrix - this%mean_data
#if defined(USE_COARRAY)
      end if
#endif
#if defined(USE_COARRAY)
      call co_broadcast(this%coeff, source_image=1)
      call co_broadcast(X_centered, source_image=1)
      sync all
      pca_X = matmul(X_centered, this%coeff,method='coarray', option='m1')
      this%matrix_app = matmul(pca_X, transpose(this%coeff), method='coarray', option='m1') + this%mean_data
#else
      pca_X = matmul(X_centered, this%coeff, method='default', option='m1')
      this%matrix_app = matmul(pca_X, transpose(this%coeff)) + this%mean_data
#endif
   end subroutine reconstruct_data
Call graph
pca calls reconstruct_data
benchmark calls pca
test1 calls pca