benchmark – ForPCA
benchmark Program
24 statements
Source File
Uses
kinds
forpca
fortime
Calls
Variables
Type Attributes Name Initial
real(kind=rk), dimension(:,:), allocatable :: matrix
real(kind=rk), dimension(:,:), allocatable :: matrix_app
real(kind=rk), dimension(:,:), allocatable :: coeff
real(kind=rk), dimension(:,:), allocatable :: score
real(kind=rk), dimension(:), allocatable :: latent
real(kind=rk), dimension(:), allocatable :: explained
type(tpca) :: p
type(timer) :: t
Source Code
program benchmark
   use kinds
   use forpca, only: tpca
   use fortime, only: timer
   implicit none
   real(rk), dimension(:,:), allocatable :: matrix
   real(rk), dimension(:,:), allocatable :: matrix_app
   real(rk), dimension(:,:), allocatable :: coeff
   real(rk), dimension(:,:), allocatable :: score
   real(rk), dimension(:),   allocatable :: latent
   real(rk), dimension(:),   allocatable :: explained
   type(tpca)                            :: p
   type(timer)                           :: t
   allocate(matrix(100,100))
#if defined(USE_COARRAY)
   sync all
   call t%timer_start()
   call p%pca(matrix, 50, 'svd', coeff, score, latent, explained, matrix_app)
   call t%timer_stop(message=' Elapsed time (benchmark: pca, coarray):')
   sync all
   call p%finalize()
#else
   call t%timer_start()
   call p%pca(matrix, 50, 'svd', coeff, score, latent, explained, matrix_app)
   call t%timer_stop(message=' Elapsed time (benchmark: pca):')
#endif
end program benchmark
Call graph
benchmark calls deallocate_tpca, pca, timer_start, timer_stop
pca calls cmp_explained_variance, compute_coeff, compute_score, initialize, reconstruct_data
compute_coeff calls eig, mask, order, svd